### ISSUE TITLE
[Documentation] Update readme so it can be published

### ISSUE THREAD

**Issue by Witteborn** [Witteborn/ReedSolomon#1]
### Tasks
- [ ] Use code examples
- [ ] how can it be installed
- [ ] add references to the source project https://www.backblaze.com/blog/reed-solomon/ and https://github.com/Backblaze/JavaReedSolomon
- [ ] create nuget
- [ ] publish it to nuget
- [ ] link nuget in readme
